AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DemoStorage:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: env0-demo-cloudformation-storage
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: lifecycle
            Status: Enabled
            ExpirationInDays: 14
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  DemoStorageBucketName:
    Description: "Name of the S3 bucket to hold demo storage"
    Value: !Ref DemoStorage
    Export:
      Name: DemoStorageBucketName

  DemoStorageBucketARN:
    Description: "ARN of the S3 bucket to hold demo storage"
    Value: !GetAtt DemoStorage.Arn
    Export:
      Name: DemoStorageBucketARN
